name: TwerkGrowth
version: 1.0
main: dev.dasischbims.twerkgrowth.Main
author: dasischbims
website: https://github.com/DasIschBims/twerkgrowth
description: TwerkGrowth is a plugin that allows you to grow trees and plants by twerking on them.
api-version: "1.20"
commands:
  tgr:
    description: Reloads the config
    usage: /twerkgrowthreload or /tgr
    permission: twerkgrowth.reload
    permission-message: You don't have permission to use this command!
    aliases: [ twerkgrowthreload ]
permissions:
  twerkgrowth.reload:
    description: Allows you to reload the config
    default: op